name: ğŸ Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia Ã  meia-noite
  workflow_dispatch:     # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v3

      - name: ğŸ Gerar animaÃ§Ã£o
        uses: Platane/snk@v3
        with:
          github_user_name: EdframGuerra
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: ğŸ’¾ Enviar para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
